replicaCount: 1
image:
  repository: birthday-app-python
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 1Gi
  mountPath: /data
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"